spring:
  application:
    name: hirehub-ai

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/hirehub?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:Athul2006}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  thymeleaf:
    cache: false

server:
  port: ${PORT:8080}

logging:
  level:
    com.hirehub: INFO
